# Set Extension name
EXTENSION = influx_cpp
DATA = influx_cpp--0.1.sql
MODULES = influx_cpp

# Boilerplate to add PGXS support
# DO NOT CHANGE
PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)
